### ISSUE TITLE
Complog should work when the output assembly doesn't exist

### ISSUE THREAD

**Issue by KirillOsenkov** [jaredpar/complog#171]
If Csc fails with errors, there's no output assembly, and complog fails with:

Missing file, either build did not happen on this machine or the environment has changed: C:\foo\obj\Debug\bar\net472\bar.dll
bar.csproj (net472)

It should tolerate this case and still create the complog

**Comment by KirillOsenkov** [comment]
Oh, wait, it did create a complog file after all, the error wasn't fatal. Not sure why I thought it was an error in the first place, I should have checked.

Perhaps it would help if you print "Wrote C:\a\b\c\foo.complog"

**Comment by jaredpar** [comment]
> Perhaps it would help if you print "Wrote C:\a\b\c\foo.complog"

That's a good suggestion. Will add that.
