### ISSUE TITLE
Unexpected complog replay error

### ISSUE THREAD

**Issue by michaelnebel** [jaredpar/complog#187]
It appears that replaying the binary log for `dotnet/msbuild` isn't succesfull even though the code builds successfully.

### How to reproduce

Install the newest version of the binary log tool.
```
 dotnet tool install --global complog --version 0.9.3 
```

Clone https://github.com/dotnet/msbuild/.

Execute the following commands from the root of they repo cloned above
```
./build.sh --restore --rebuild --binarylog 
complog replay -f net9.0 artifacts/log/Debug/Build.binlog
``` 

The replay produces thousands of errors like
```
StringTools.UnitTests.csproj (net9.0) ...Error
    CS0122: 'WeakStringCache' is inaccessible due to its protection level
    CS0122: 'WeakStringCache' is inaccessible due to its protection level
    CS0122: 'WeakStringCache.Dispose()' is inaccessible due to its protection level
    CS0122: 'InternableString' is inaccessible due to its protection level
    CS0122: 'InternableString' is inaccessible due to its protection level
    CS0122: 'WeakStringCache.GetOrCreateEntry(ref InternableString, out bool)' is inaccessible due to its protection level
```

It is worth mentioning that
```
./build.sh --restore --rebuild
```
builds cleanly.

**Comment by jaredpar** [comment]
@michaelnebel at a glance I suspect this is an issue where I'm getting the compilation name wrong and breaking IVT. Will take a look.

**Comment by jaredpar** [comment]
Yeah that was the case. When reading from a binary log directly the compilation name was being set to Microsoft.NET.StringTools.UnitTests.dll instead of Microsoft.NET.StringTools.UnitTests and that was breaking IVT. Fix on the way.

**Comment by michaelnebel** [comment]
@jaredpar : Uh, thank you very much for the quick fix - I really appreciate it!!!
